export const formFields = [
  {
    type: "text",
    title: "Product Name",
    id: "product-name",
    name: "title",
  },
  {
    type: "number",
    title: "Product Price",
    id: "product-price",
    name: "price",
  },
  {
    type: "textarea",
    title: "Product Description",
    name: "desc",
  },
  {
    type: "select",
    title: "Condition",
    id: "product-condition",
    name: "condition",
    options: ["new", "slightly used", "used"],
  },
  {
    type: "text",
    title: "Vendor",
    id: "product-vendor",
    name: "vendor",
    default: "Black Storm Technologies",
  },
  {
    type: "text",
    title: "Brand",
    id: "product-brand",
    name: "brand",
  },
  {
    type: "select",
    title: "Category",
    id: "product-category",
    name: "category",
    options: ["gaming", "designer", "office"],
  },
  {
    type: "checkbox",
    title: "Featured",
    id: "product-featured",
    name: "featured",
  },
  {
    type: "number",
    title: "Weight",
    id: "product-weight",
    name: "weight",
  },
  {
    type: "text",
    title: "Tags",
    id: "product-tags",
    name: "tags",
  },
  {
    type: "number",
    title: "In Stock",
    id: "product-in-stock",
    name: "stock",
  },
  // {
  //   type: "text",
  //   title: "Additional Information",
  //   id: "product-additional-info",
  //   name: "additional_info",
  // },
  {
    type: "file",
    title: "Social Image",
    id: "product-social-image",
    name: "social_image",
  },
  {
    type: "file",
    title: "Product Image 1",
    id: "product-image-1",
    name: "image_1",
  },
  {
    type: "file",
    title: "Product Image 2",
    id: "product-image-2",
    name: "image_2",
  },
  {
    type: "select",
    title: "Processor Type",
    id: "product-processor-type",
    name: "processor_type",
    options: ["Intel", "AMD"],
  },
  {
    type: "select",
    title: "Processor Model",
    id: "product-processor-model",
    name: "processor_model",
    options: ["core i3", "core i5", "core i7", "core i9"],
  },
  {
    type: "decimal",
    step: "0.1",
    title: "Processor Speed",
    id: "product-processor-speed",
    name: "processor_speed",
  },
  {
    type: "select",
    title: "Storage Type",
    id: "product-storage-type",
    name: "storage_type",
    options: ["HDD", "SSD"],
  },
  {
    type: "number",
    title: "Storage Size",
    id: "product-storage-size",
    name: "storage_size",
  },
  {
    type: "select",
    title: "RAM Model",
    id: "product-ram-model",
    name: "ram_model",
    options: ["DDR3", "DDR4"],
  },
  {
    type: "number",
    title: "RAM Size",
    id: "product-ram-size",
    name: "ram_size",
  },
  {
    type: "text",
    title: "Graphics Card",
    id: "product-graphics-card",
    name: "graphics_card",
  },
];

export const socialConfirmFields = [
  {
    type: "checkbox",
    title: "Post to Facebook",
    id: "post-to-facebook",
    name: "post_to_facebook",
  },
  {
    type: "checkbox",
    title: "Post to Telegram",
    id: "post-to-telegram",
    name: "post_to_telegram",
  },
];
